apiVersion: v1
kind: Secret
metadata:
  name: e-secret
  namespace: e-commerce

type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: mydb

  DB_NAME: mydb
  DB_USER: root
  DB_PASSWORD: root
  DB_HOST: mysql-svc
  DB_PORT: "3306"
