# Generated by Django 5.1.3 on 2025-12-16 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='O_tracker',
            fields=[
                ('otid', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('oid', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.BigIntegerField()),
                ('address', models.TextField(max_length=100)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('amount', models.FloatField(default=0)),
                ('zip', models.IntegerField()),
                ('payment', models.CharField(max_length=20)),
                ('odate', models.DateTimeField(auto_now_add=True)),
                ('charges', models.IntegerField(default=0)),
                ('order_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.o_tracker')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=50)),
                ('pprice', models.IntegerField()),
                ('pdis', models.TextField()),
                ('pimage', models.ImageField(upload_to='product')),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.category')),
            ],
        ),
        migrations.CreateModel(
            name='O_item',
            fields=[
                ('O_item', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('subtotal', models.IntegerField()),
                ('o_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.order')),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('crt_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('w_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.product')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
